import numpy as np


WRAP_IDS = [
    "INA10000",
    "INA20000",
    "INA30000",
    "INB10000",
    "INB20000",
    "INB30000",
    "INB40000",
    "INC10000",
    "INC20000",
    "INC30000",
    "INC40000",
    "INC50000",
    "INC60000",
    "INC70000",
    "IND10000",
    "IND20000",
    "IND30000",
    "IND40000",
    "INE10000",
    "INE20000",
    "INE30000",
    "INE40000",
    "INF10000",
    "INF20000",
    "INF30000",
    "ING10000",
    "ING20000",
    "ING30000",
    "ING40000",
    "ING50000",
    "INH10000",
    "INH20000",
    "INI10000",
    "INI20000",
    "INI30000",
    "INI40000",
    "INJ10000",
    "INJ20000",
    "INJ30000",
    "INJ40000",
    "INJ50000",
    "INK10000",
    "INK20000",
    "INL10000",
    "INL20000",
]

N_HEADER = 5

COL_DIVERSION_RIGHTS = [
    dict(name='year', dtype=np.int16, length=4),
    dict(name='month', dtype=np.int16, length=2),
    dict(name='diversion_or_energy_shortage', dtype=np.float32, length=11),
    dict(name='diversion_or_energy_target', dtype=np.float32, length=11),
    dict(name='evaporation_precip_volume', dtype=np.float32, length=11),
    dict(name='end_of_period_storage', dtype=np.float32, length=11),
    dict(name='stream_flow_depletion', dtype=np.float32, length=11),
    dict(name='available_stream_flow', dtype=np.float32, length=11),
    dict(name='releases_from_other_reservoirs', dtype=np.float32, length=11),
    dict(name='water_right_identifier', dtype=str, length=16),
    dict(name='group_identifier', dtype=str, length=8),
    dict(name='group_identifier', dtype=str, length=8),
    dict(name='return_flow', dtype=np.float32, length=11),
    dict(name='increase_in_available_flow', dtype=np.float32, length=10),
]

COL_FLOW_RIGHTS = [
    dict(name='IF', dtype=str, length=2),
    dict(name='month', dtype=np.int16, length=4),
    dict(name='reservoir_release_shortage', dtype=np.float32, length=11),
    dict(name='required_reservoir_release', dtype=np.float32, length=11),
    dict(name='evaporation_precip_volume', dtype=np.float32, length=11),
    dict(name='end_of_period_storage', dtype=np.float32, length=11),
    dict(name='stream_flow_depletion', dtype=np.float32, length=11),
    dict(name='available_stream_flow', dtype=np.float32, length=11),
    dict(name='releases_from_other_reservoirs', dtype=np.float32, length=11),
    dict(name='water_right_identifier', dtype=str, length=16),
    dict(name='instream_flow_target', dtype=np.float32, length=11),
    dict(name='instream_flow_shortage', dtype=np.float32, length=11),
    dict(name='target_and_FSV_volume', dtype=np.float32, length=11),
    dict(name='flow_switch_count', dtype=np.int16, length=14),
]

COL_CONTROL_POINTS = [
    dict(name='control_point_identifier', dtype=str, length=6),
    dict(name='diversion_shortage', dtype=np.float32, length=11),
    dict(name='diversion_target', dtype=np.float32, length=11),
    dict(name='reservoir_evaporation_precipitation', dtype=np.float32, length=11),
    dict(name='end_of_period_storage', dtype=np.float32, length=11),
    dict(name='stream_flow_depletion', dtype=np.float32, length=11),
    dict(name='unappropriated_stream_flow', dtype=np.float32, length=11),
    dict(name='return_flows_returning_here', dtype=np.float32, length=11),
    dict(name='naturalized_stream_flows', dtype=np.float32, length=11),
    dict(name='regulated_stream_flows', dtype=np.float32, length=11),
    dict(name='channel_loss_credits', dtype=np.float32, length=8),
    dict(name='channel_losses', dtype=np.float32, length=7),
    dict(name='upstream_reservoir_releases', dtype=np.float32, length=8),
    dict(name='instream_flow_target', dtype=np.float32, length=8),
]

COL_RESERVOIR = [
    dict(name='reservoir_identifier', dtype=str, length=6),
    dict(name='hydropower_shortage_or_secondary_energy', dtype=np.float32, length=11),
    dict(name='energy_generated', dtype=np.float32, length=11),
    dict(name='reservoir_net_evaporation_precipitation_volume', dtype=np.float32, length=11),
    dict(name='end_of_period_reservoir_storage_volume', dtype=np.float32, length=11),
    dict(name='inflows_to_reservoir_from_stream_flow_depletions', dtype=np.float32, length=11),
    dict(name='inflows_to_reservoir_from_releases_from_other_reservoirs', dtype=np.float32, length=11),
    dict(name='reservoir_releases_accessible_to_hydroelectric_power_turbines', dtype=np.float32, length=11),
    dict(name='reservoir_releases_not_accessible_to_hydroelectric_power_turbines', dtype=np.float32, length=11),
    dict(name='adjusted_evaporation_precipitation_depths', dtype=np.float32, length=11),
    dict(name='evaporation_precipitation_depths', dtype=np.float32, length=11),
    dict(name='reservoir_water_surface_elevation', dtype=np.float32, length=11),
    dict(name='reservoir_storage_capacity', dtype=np.float32, length=9),
]

COL_WATER_RIGHT = [
    dict(name='record_type', dtype=str, length=2),
    dict(name='control_point_identifier', dtype=str, length=6),
    dict(name='amount', dtype=np.float32, length=8),
    dict(name='use', dtype=str, length=8),
    dict(name='priority_number', dtype=np.int16, length=8),
    dict(name='water_right_type', dtype=np.int16, length=4),
    dict(name='return_flow_specification', dtype=np.int16, length=4),
    dict(name='return_flow_factor_or_monthly_flow_identifier', dtype=str, length=8),
    dict(name='return_flow_control_point', dtype=str, length=8),
    dict(name='flow_switch_or_cumulative_volume_identifier', dtype=np.int16, length=4),
    dict(name='dought_index_identifier', dtype=np.int16, length=4),
    dict(name='water_right_identifier', dtype=str, length=16),
    dict(name='water_right_group_identifier_1', dtype=str, length=8),
    dict(name='water_right_group_identifier_2', dtype=str, length=8),
    dict(name='alternate_water_right_identifier', dtype=str, length=16),
    dict(name='alternate_water_right_group_identifier_1', dtype=str, length=8),
    dict(name='alternate_water_right_group_identifier_2', dtype=str, length=8),
]